schema-version = "1.10.0"


## Install Packages --------------------------------------------------
[install]
gh.pkg-path = "gh"
jq.pkg-path = "jq"
gum.pkg-path = "gum"
bash.pkg-path = "bash"
coreutils.pkg-path = "coreutils"
less.pkg-path = "less"
cargo.pkg-path = "cargo"
pkg-config.pkg-path = "pkg-config"
rustc.pkg-path = "rustc"


## Environment Variables ---------------------------------------------
[vars]


## Activation Hook ---------------------------------------------------
[hook]


## Profile script ----------------------------------------------------
[profile]


## Services ---------------------------------------------------------
[services]


## Include ----------------------------------------------------------
[include]


## Build and publish your own packages ------------------------------
[build]


## Other Environment Options -----------------------------------------
[options]
